CactusDepotProd/CactusDepot.Seeds/Areas/Identity/Pages/Account/AccessDenied.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CactusDepot.Seeds.Areas.Identity.Pages.Account
{
    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    public class AccessDeniedModel : PageModel
    {
        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public void OnGet()
        {
        }
    }
}

CactusDepotProd/CactusDepot.Seeds/Controllers/Books/BooksController.cs
using CactusDepot.Shared;
using CactusDepot.Shared.DataContext;
using CactusDepot.Shared.Models;
using CactusDepot.Shared.Models.Seeds;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CactusDepot.Seeds.Controllers.Books
{
    [Authorize(Roles = "Administrator,Manager,SuperAdmin")]
    public partial class BooksController : Controller
    {
        public const string ErrorMessageILoggerFactoryIsNull = "ILoggerFactory is null";

        private readonly SeedsDbContext _context;
        private readonly ILogger<CactusSeed> _logger;
        private readonly IWebHostEnvironment _hostingWebEnvironment;
        private readonly IHostEnvironment _hostingAppEnvironment;
        private readonly string _uploadsFolder;
        //private readonly ISeedsRepository _seedsRepository;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="context"></param>
        /// <param name="logger"></param>
        public BooksController(SeedsDbContext context, ILogger<CactusSeed> logger, IWebHostEnvironment hostingEnvironment, IHostEnvironment hostingAppEnvironment)//, ISeedsRepository seedsRepository)
        {
            _context = context;
            _logger = logger;
            _logger.LogInformation("BooksController init");
            SharedUtil.WriteLogToConsole("BooksController", "Constructor started");
            _hostingWebEnvironment = hostingEnvironment ?? throw new ArgumentNullException(nameof(hostingEnvironment));
            _hostingAppEnvironment = hostingAppEnvironment ?? throw new ArgumentNullException(nameof(hostingAppEnvironment));
            _uploadsFolder = Path.Combine(_hostingAppEnvironment.ContentRootPath, "Db", "Images");//path "/app/Db/Images"
            //_seedsRepository = seedsRepository;
            SharedUtil.WriteLogToConsole("BooksController", "Constructor completed");
        }

        #region Index

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Index(string searchString, int p = 1)
        {
            _logger.LogInformation("BooksController.Index()");
            SharedUtil.WriteLogToConsole("BooksController", "GET.Index() started");

            //IQueryable<CactusSeed> seedsOrderBy = from m in _context.CactusSeeds orderby m.SeedCollectedDate descending select m;

            //PagedResult<CactusSeed> seeds = seedsOrderBy.GetPaged(p, 12);
            //if (!string.IsNullOrEmpty(searchString))
            //{
            //    seeds = _context.CactusSeeds.Where(s => s.SeedName.Contains(searchString)).GetPaged(p, 12);
            //}
            SharedUtil.WriteLogToConsole("BooksController", "GET.Index() returning");
            //return View(seeds);
            return View("UnderContruction");
        }
        #endregion
    }
}

CactusDepotProd/CactusDepot.Seeds/Controllers/HealthController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Diagnostics.HealthChecks;
using Microsoft.Extensions.DependencyInjection;
using System.Net;
using NuGet.Protocol;

namespace CactusDepot.Seeds.Controllers
{
    public class HealthController : Controller
    {
        private readonly ILogger<HealthController> _logger;
        private readonly IHealthCheck _service;
        private readonly HealthCheckContext _context;

        public HealthController(ILogger<HealthController> logger, IHealthCheck service, HealthCheckContext context)
        {
            _logger = logger;
            _service = service;
            _context = context;
        }


        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var report = await _service.CheckHealthAsync(_context);
            var reportToJson = report.ToJson();

            _logger.LogInformation($"Get Health Information: {reportToJson}");

            return report.Status == HealthStatus.Healthy ? Ok(reportToJson) : StatusCode((int)HttpStatusCode.ServiceUnavailable, reportToJson);
        }
    }
}

CactusDepotProd/CactusDepot.Seeds/Controllers/Plants/PlantsController.cs
using CactusDepot.Shared;
using CactusDepot.Shared.DataContext;
using CactusDepot.Shared.Models;
using CactusDepot.Shared.Models.Seeds;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CactusDepot.Seeds.Controllers.Plants
{
    [Authorize(Roles = "Administrator,Manager,SuperAdmin")]
    public partial class PlantsController : Controller
    {
        public const string ErrorMessageILoggerFactoryIsNull = "ILoggerFactory is null";

        private readonly SeedsDbContext _context;
        private readonly ILogger<CactusSeed> _logger;
        private readonly IWebHostEnvironment _hostingWebEnvironment;
        private readonly IHostEnvironment _hostingAppEnvironment;
        private readonly string _uploadsFolder;
        //private readonly ISeedsRepository _seedsRepository;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="context"></param>
        /// <param name="logger"></param>
        public PlantsController(SeedsDbContext context, ILogger<CactusSeed> logger, IWebHostEnvironment hostingEnvironment, IHostEnvironment hostingAppEnvironment)//, ISeedsRepository seedsRepository)
        {
            _context = context;
            _logger = logger;
            _logger.LogInformation("PlantsController init");
            SharedUtil.WriteLogToConsole("PlantsController", "Constructor started");
            _hostingWebEnvironment = hostingEnvironment ?? throw new ArgumentNullException(nameof(hostingEnvironment));
            _hostingAppEnvironment = hostingAppEnvironment ?? throw new ArgumentNullException(nameof(hostingAppEnvironment));
            _uploadsFolder = Path.Combine(_hostingAppEnvironment.ContentRootPath, "Db", "Images");//path "/app/Db/Images"
            //_seedsRepository = seedsRepository;
            SharedUtil.WriteLogToConsole("PlantsController", "Constructor completed");
        }

        #region Index

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Index(string searchString, int p = 1)
        {
            _logger.LogInformation("PlantsController.Index()");
            SharedUtil.WriteLogToConsole("PlantsController", "GET.Index() started");

            //IQueryable<CactusSeed> seedsOrderBy = from m in _context.CactusSeeds orderby m.SeedCollectedDate descending select m;

            //PagedResult<CactusSeed> seeds = seedsOrderBy.GetPaged(p, 12);
            //if (!string.IsNullOrEmpty(searchString))
            //{
            //    seeds = _context.CactusSeeds.Where(s => s.SeedName.Contains(searchString)).GetPaged(p, 12);
            //}
            SharedUtil.WriteLogToConsole("PlantsController", "GET.Index() returning");
            //return View(seeds);
            return View("UnderContruction");
        }
        #endregion
    }
}

CactusDepotProd/CactusDepot.Seeds/Controllers/Seeds/SeedsController.cs
using CactusDepot.Shared;
using CactusDepot.Shared.DataContext;
using CactusDepot.Shared.Models;
using CactusDepot.Shared.Models.Seeds;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CactusDepot.Seeds.Controllers
{
    //[AllowAnonymous]
    //[Authorize]
    //[Authorize("ApprovedUser")]
    //[Authorize(Roles = "Administrator")]

    [Authorize(Roles = "Administrator,Manager,SuperAdmin")]
    public partial class SeedsController : Controller
    {
        public const string ErrorMessageILoggerFactoryIsNull = "ILoggerFactory is null";

        private readonly SeedsDbContext _context;
        private readonly ILogger<CactusSeed> _logger;
        private readonly IWebHostEnvironment _hostingWebEnvironment;
        private readonly IHostEnvironment _hostingAppEnvironment;
        private readonly string _uploadsFolder;
        //private readonly ISeedsRepository _seedsRepository;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="context"></param>
        /// <param name="logger"></param>
        public SeedsController(SeedsDbContext context, ILogger<CactusSeed> logger, IWebHostEnvironment hostingEnvironment, IHostEnvironment hostingAppEnvironment)//, ISeedsRepository seedsRepository)
        {
            _context = context;
            _logger = logger;
            _logger.LogInformation("SeedsController init");
            SharedUtil.WriteLogToConsole("SeedsController", "Constructor started");
            _hostingWebEnvironment = hostingEnvironment ?? throw new ArgumentNullException(nameof(hostingEnvironment));
            _hostingAppEnvironment = hostingAppEnvironment ?? throw new ArgumentNullException(nameof(hostingAppEnvironment));
            _uploadsFolder = Path.Combine(_hostingAppEnvironment.ContentRootPath, "Db", "Images");//path "/app/Db/Images"
            //_seedsRepository = seedsRepository;
            SharedUtil.WriteLogToConsole("SeedsController", "Constructor completed");
        }

        #region Index

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Index(string searchString, int p = 1)
        {
            _logger.LogInformation("SeedsController.Index()");
            SharedUtil.WriteLogToConsole("SeedsController", "GET.Index() started");
            IQueryable<CactusSeed> seedsOrderBy = from m in _context.CactusSeeds orderby m.SeedCollectedDate descending select m;

            PagedResult<CactusSeed> seeds = seedsOrderBy.GetPaged(p, 12);
            if (!string.IsNullOrEmpty(searchString))
            {
                seeds = _context.CactusSeeds.Where(s => s.SeedName.Contains(searchString)).GetPaged(p, 12);
            }
            SharedUtil.WriteLogToConsole("SeedsController", "GET.Index() returning");
            return View(seeds);
        }
        #endregion


        #region Json list - testing an API style of return
        //[AllowAnonymous]
        [Authorize]
        [HttpGet]
        public JsonResult GetSeedsJson(string searchString)
        {
            IQueryable<CactusSeed> seeds = from m in _context.CactusSeeds select m;
            if (!string.IsNullOrEmpty(searchString))
            {
                seeds = seeds.Where(s => s.SeedName.Contains(searchString));
            }
            return Json(seeds);
        }
        #endregion
        
    }
}

CactusDepotProd/CactusDepot.Seeds/Views/Shared/AccessDenied.cshtml
@page
@{
	ViewBag.Title = "Not Found";
}

<header>
	<h1 class="text-danger">@ViewBag.Title</h1>
	<h1 class="text-danger">@ViewBag.Endpoint</h1>
	<h6>The resource you are trying to get Not Found</h6>
	<hr />
	<img src="~/images/noaccess.png" style="height:300px;width:300px" />
</header>

CactusDepotProd/CactusDepot.Seeds/Views/Shared/NotFound.cshtml
@page
@{
	ViewBag.Title = "Not Found";
}

<header>
	<h1 class="text-danger">@ViewBag.Title</h1>
	<h1 class="text-danger">@ViewBag.Endpoint</h1>
	<h6>The resource you are trying to get Not Found</h6>
	<hr />

	<img src="~/images/status-code/404-not-found.png" style="height:150px;width:300px" />
</header>

<body>
	<div>
	<a  href="https://www.drlinkcheck.com/blog/free-http-error-images">
		Credits
	</a>
	</div>
</body>

CactusDepotProd/CactusDepot.Seeds/Views/Shared/UnderContruction.cshtml
@page
@{
	ViewBag.Title = "Under Contruction";
}

<header>
	<h1 class="text-danger">@ViewBag.Title</h1>
	<h1 class="text-danger">@ViewBag.Endpoint</h1>
	<h6>The resource you are trying to get Not Ready</h6>
	<hr />

	<img src="~/images/status-code/418-im-a-teapot.png" style="height:150px;width:300px" />
</header>

<body>
	<div>
	<a  href="https://www.drlinkcheck.com/blog/free-http-error-images">
		Credits
	</a>
	</div>
</body>

CactusDepotProd/CactusDepot.Seeds/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <environment include="Development">
        <script src="~/lib/bootstrap/dist/css/bootstrap.css"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>      
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>      
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>      
        <script src="~/lib/dist/js/bootstrap.js"></script>  
    </environment>
    <environment exclude="Development">
        <script src="~/lib/bootstrap/dist/css/bootstrap.css"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>      
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>      
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>      
        <script src="~/lib/dist/js/bootstrap.js"></script>         
    </environment>
    <title>@ViewData["Title"] - Cactus Depot</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="@Url.Content("~/css/catalog.css")" rel="stylesheet" type="text/css" />

    <link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/regular.min.css">
    <link rel="stylesheet" href="~/lib/font-awesome/css/solid.min.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">

                <div>
                    <img class="spaceright" src="~/images/logo_small_orange.png" title="cacti corner" alt="cacticorner.ca" style="margin-right: 10px;" /> 
                </div>

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cactus Depot</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>


                        <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Categories
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Seeds" asp-action="CatalogPages">Seeds</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Plants" asp-action="Index">Plants</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                                </div>

                        </li> 

                        @if(signInManager.IsSignedIn(User) && (User.IsInRole("Administrator") || User.IsInRole("SuperAdmin")))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Admin
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" asp-area="" asp-controller="Administration" asp-action="ListRoles">Roles</a>    
                                    <a class="dropdown-item" asp-area="" asp-controller="Administration" asp-action="ListUsers">Users</a>    
                                </div>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Health" asp-action="Index">Health check</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year.ToString() - Cactus Plants Catalog of Vladimir Andrenkov ver.008 - <a asp-area="" asp-controller="Home" asp-action="About">About</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/CustomScript.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>